replicas: 1

tempo:
  registry: 10.10.10.10:5000/docker.io
  repository: grafana/tempo
  tag: 2.9.0
  retention: 6h
  memBallastSizeMbs: 64
  storage:
    trace:
      backend: local
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

persistence:
  enabled: true
  storageClassName: ""
  size: 4Gi

nodeSelector:
  workload.medical-platform.io/tier: platform

serviceMonitor:
  enabled: false
