apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: patient-db
spec:
  serviceName: patient-db
  replicas: 1
  selector:
    matchLabels:
      app: patient-db
  template:
    metadata:
      labels:
        app: patient-db
    spec:
      containers:
        - name: patient-db
          image: postgres:15
          args:
            - -c
            - shared_buffers=16MB
            - -c
            - effective_cache_size=64MB
            - -c
            - work_mem=1MB
            - -c
            - maintenance_work_mem=16MB
            - -c
            - max_connections=20
          ports:
            - containerPort: 5432
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - user
                - -d
                - patient_db
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: patient_db
          volumeMounts:
            - name: patient-db-storage
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              cpu: 50m
              memory: 96Mi
            limits:
              memory: 192Mi
  volumeClaimTemplates:
    - metadata:
        name: patient-db-storage
      spec:
        volumeName: patient-db-pv
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
