apiVersion: v1
kind: Namespace
metadata:
  name: medical-auth
---
apiVersion: v1
kind: Namespace
metadata:
  name: medical-messaging
---
apiVersion: v1
kind: Namespace
metadata:
  name: medical-patient
---
apiVersion: v1
kind: Namespace
metadata:
  name: medical-appointment
---
apiVersion: v1
kind: Namespace
metadata:
  name: medical-prescription
---
apiVersion: v1
kind: Namespace
metadata:
  name: medical-notification
---
apiVersion: v1
kind: Namespace
metadata:
  name: medical-dashboard
