apiVersion: apps/v1
kind: Deployment
metadata:
  name: prescription-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prescription-service
  template:
    metadata:
      labels:
        app: prescription-service
    spec:
      containers:
        - name: prescription-service
          image: zexpand/prescription-service:latest
          ports:
            - containerPort: 8083
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-server:8761/eureka/
            - name: SPRING_DATASOURCE_URL
              value: jdbc:h2:mem:prescription_db;DB_CLOSE_DELAY=-1
            - name: SPRING_DATASOURCE_USERNAME
              value: sa
            - name: SPRING_DATASOURCE_PASSWORD
              value: ""
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
