apiVersion: v1
kind: PersistentVolume
metadata:
  name: patient-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/patient-db
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: appointment-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/appointment-db
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prescription-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/prescription-db
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/kafka
