apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: zexpand/api-gateway:latest
          ports:
            - containerPort: 8080
          env:
            - name: EUREKA_CLIENT_ENABLED
              value: "false"
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:+UseSerialGC -Xms64m -Xmx128m -XX:MaxMetaspaceSize=128m -XX:ReservedCodeCacheSize=48m -Xss256k -Djava.security.egd=file:/dev/./urandom"
          resources:
            requests:
              cpu: 50m
              memory: 160Mi
            limits:
              memory: 320Mi
