apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../storage
  - ../../db/patient-db
  - ../../db/appointment-db
  - ../../db/prescription-db
  - ../../db/notification-db
  - ../../kafka
