apiVersion: v1
kind: PersistentVolume
metadata:
  name: patient-db-pv
  labels:
    app: patient-db
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/patient-db
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: appointment-db-pv
  labels:
    app: appointment-db
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/appointment-db
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prescription-db-pv
  labels:
    app: prescription-db
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/prescription-db
