apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-service
  template:
    metadata:
      labels:
        app: patient-service
    spec:
      containers:
        - name: patient-service
          image: zexpand/patient-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: EUREKA_CLIENT_ENABLED
              value: "false"
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:+UseSerialGC -Xms48m -Xmx96m -XX:MaxMetaspaceSize=128m -XX:ReservedCodeCacheSize=48m -Xss256k -Djava.security.egd=file:/dev/./urandom"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:h2:mem:patient_db;DB_CLOSE_DELAY=-1
            - name: SPRING_DATASOURCE_USERNAME
              value: sa
            - name: SPRING_DATASOURCE_PASSWORD
              value: ""
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 256Mi
