[kube_control_plane]
control-plane-1 ansible_host=10.10.10.10 ansible_user=vagrant ansible_port=22 ansible_ssh_private_key_file=providers/local-vagrant/.vagrant/machines/control-plane-1/vmware_desktop/private_key

[kube_workers]
worker-1 ansible_host=10.10.10.11 ansible_user=vagrant ansible_port=22 ansible_ssh_private_key_file=providers/local-vagrant/.vagrant/machines/worker-1/vmware_desktop/private_key
worker-2 ansible_host=10.10.10.12 ansible_user=vagrant ansible_port=22 ansible_ssh_private_key_file=providers/local-vagrant/.vagrant/machines/worker-2/vmware_desktop/private_key

[k8s_cluster:children]
kube_control_plane
kube_workers

[k8s_cluster:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
