apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: medical-platform
resources:
  - ../../../base/deps
  - local-pv.yaml
images:
  - name: postgres
    newName: 10.10.10.10:5000/postgres
    newTag: "15"
  - name: apache/kafka
    newName: 10.10.10.10:5000/apache/kafka
    newTag: "3.8.1"
  - name: busybox
    newName: 10.10.10.10:5000/busybox
    newTag: "1.36"
patches:
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: patient-db
    patch: |-
      - op: add
        path: /spec/template/spec/affinity
        value:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: kubernetes.io/hostname
                      operator: In
                      values:
                        - data-1
                        - postgres-1
                        - worker-1
                        - worker-2
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: appointment-db
    patch: |-
      - op: add
        path: /spec/template/spec/affinity
        value:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: kubernetes.io/hostname
                      operator: In
                      values:
                        - data-1
                        - postgres-1
                        - worker-1
                        - worker-2
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: prescription-db
    patch: |-
      - op: add
        path: /spec/template/spec/affinity
        value:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: kubernetes.io/hostname
                      operator: In
                      values:
                        - data-1
                        - postgres-1
                        - worker-1
                        - worker-2
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: kafka
    patch: |-
      - op: add
        path: /spec/template/spec/affinity
        value:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: kubernetes.io/hostname
                      operator: In
                      values:
                        - data-1
                        - kafka-1
                        - worker-1
                        - worker-2
  - target:
      version: v1
      kind: PersistentVolume
      name: patient-db-pv
    patch: |-
      - op: add
        path: /spec/nodeAffinity
        value:
          required:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - data-1
                      - postgres-1
                      - worker-1
                      - worker-2
  - target:
      version: v1
      kind: PersistentVolume
      name: appointment-db-pv
    patch: |-
      - op: add
        path: /spec/nodeAffinity
        value:
          required:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - data-1
                      - postgres-1
                      - worker-1
                      - worker-2
  - target:
      version: v1
      kind: PersistentVolume
      name: prescription-db-pv
    patch: |-
      - op: add
        path: /spec/nodeAffinity
        value:
          required:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - data-1
                      - postgres-1
                      - worker-1
                      - worker-2
  - target:
      version: v1
      kind: PersistentVolume
      name: kafka-pv
    patch: |-
      - op: add
        path: /spec/nodeAffinity
        value:
          required:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - data-1
                      - kafka-1
                      - worker-1
                      - worker-2
