apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: medical-platform-dev
  namespace: argocd
spec:
  project: medical-platform
  source:
    repoURL: https://github.com/asdqwce/cloudnative_study.git
    targetRevision: release/dev
    path: k8s/overlays/aws/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: medical-platform-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
